FROM python:3.10-slim

WORKDIR /frontend

COPY requirements.frontend.txt .

RUN pip install --no-cache-dir -r requirements.frontend.txt

COPY src/streamlit/ .

COPY src/static/css/ src/static/css/

EXPOSE 8501

HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

ENTRYPOINT ["streamlit", "run", "ui.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
