FROM python:3.12-slim-bookworm

ARG UV_VERSION=0.7.9
COPY --from=ghcr.io/astral-sh/uv:${UV_VERSION} /uv /uvx /bin/

WORKDIR /backend

COPY pyproject.toml uv.lock ./
RUN touch README.md

RUN uv sync --locked --no-dev

COPY src/app src/app

COPY src/data src/data

COPY src/model src/model

COPY src/static src/static

COPY src/templates src/templates

EXPOSE 8080

ENTRYPOINT ["uv", "run", "uvicorn", "src.app.main:app", "--host", "0.0.0.0", "--port", "8080"]
