services:
  postgres:
    image: postgres:latest
    container_name: database-container
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: predictions
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Password!
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    networks:
      - deploy_network

  backend:
    image: happyregistry.azurecr.io/happymeter-backend:1
    container_name: backend-container
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: predictions
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Password!
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - deploy_network

  frontend:
    image: happyregistry.azurecr.io/happymeter-frontend:1
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend-container
    ports:
      - 8501:8501
    environment:
      BACKEND_HOST: backend:8080
    depends_on:
      - backend
    networks:
      - deploy_network

networks:
  deploy_network:
    driver: bridge

volumes:
  postgres_data:
