FROM python:3.10-slim

WORKDIR /backend

COPY requirements.backend.txt .

RUN pip install --no-cache-dir -r requirements.backend.txt

COPY src/app src/app

COPY src/data src/data

COPY src/model src/model

COPY src/static src/static

EXPOSE 8080

CMD ["uvicorn", "src.app.main:app", "--host", "0.0.0.0", "--port", "8080"]
