name: happymeter
channels:
  - default
  - conda-forge
dependencies:
  - python==3.7
  - fastapi==0.63.0
  - uvicorn==0.13.4
  - Jinja2==2.11.3
  - pandas==1.2.3
  - scikit-learn==0.24.1
  - pydantic==1.8.1
  - joblib==1.0.1
  - pytest==6.2.3
  - requests==2.22.0
  - aiofiles==0.6.0
  - certifi==2020.12.5
